import geopandas as gpd
from shapely.geometry import Polygon


def add_flooding_information_to_buildings(
    buildings: gpd.GeoDataFrame, flooding_data: gpd.GeoDataFrame
) -> gpd.GeoDataFrame:
    """
    # todo Generated by github copilot and needs to be tested
    Adds a column to the buildings dataframe that indicates whether the building is flooded or not.
    :param buildings:
    :param flooding_data:
    :return:
    """
    buildings["flooding"] = buildings.intersects(flooding_data)
    return buildings


def add_flooding_information_to_buildings_using_polygon(
    buildings: gpd.GeoDataFrame, polygon: Polygon
) -> gpd.GeoDataFrame:
    """
    # todo Generated by github copilot and needs to be tested
    Adds a column to the buildings dataframe that indicates whether the building is flooded or not.
    :param buildings:
    :param polygon:
    :return:
    """
    buildings["flooding"] = buildings.intersects(polygon)
    return buildings


def get_indicis_of_buildings_that_intersect_with_polygons(
    buildings: gpd.GeoDataFrame, polygons: gpd.GeoDataFrame
) -> set:
    set_of_flooded_buildings = set()
    for i in range(len(polygons)):
        # for i in range(2):
        print(f"Processing polygon {i} of {len(polygons)}")
        polygon = polygons.loc[i, "geometry"]
        mask = buildings.within(polygon)
        # mask = ~mask # inverts the mask
        # buildings_within_polygon.update(buildings[buildings.within(polygon)].index)
        set_of_flooded_buildings.update(buildings[mask].index)

    return set_of_flooded_buildings


def get_buildings_that_intersect_with_polygons(
    buildings: gpd.GeoDataFrame, polygons: gpd.GeoDataFrame
) -> gpd.GeoDataFrame:
    set_of_flooded_buildings = get_indicis_of_buildings_that_intersect_with_polygons(buildings, polygons)
    flooded_buildings = buildings.loc[set_of_flooded_buildings]
    return flooded_buildings


def add_flooding_flag_to_buildings(buildings: gpd.GeoDataFrame, polygons: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    set_of_flooded_buildings = get_indicis_of_buildings_that_intersect_with_polygons(buildings, polygons)
    buildings["flooded"] = buildings.index.isin(set_of_flooded_buildings)
    # buildings_in_flooded_area["flooded"] = False
    # buildings.loc[set_of_flooded_buildings, "flooded"] = True
    return buildings
