import logging

import geopandas as gpd
from shapely.geometry import Polygon
import fiona

logger = logging.getLogger(__name__)


# function that filters buildings by a polygon
def filter_buildings_by_polygon(buildings: gpd.GeoDataFrame, polygon: Polygon) -> gpd.GeoDataFrame:
    buildings_clipped = buildings.clip(polygon)
    return buildings_clipped


def get_layers_from_gpkg_file_as_dict(gpkg_file_path: str) -> dict:
    # todo this is generated by github copilot and needs to be tested
    layers = {}
    with fiona.open(gpkg_file_path) as src:
        for layer in src:
            layers[layer] = src[layer]
    return layers


def filter_gdf_from_list_of_polygons(data: gpd.GeoDataFrame, polygons: list[Polygon]) -> gpd.GeoDataFrame:
    # todo this is generated by github copilot and needs to be tested
    id_mask = set()
    for polygon in polygons:
        id_mask.add(data[data.intersects(polygon)])

    return data.loc[list(id_mask)]


def filter_gdf_from_from_gdf(data: gpd.GeoDataFrame, filter_data: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    # todo this is generated by github copilot and needs to be tested
    id_mask = set()
    for polygon in filter_data.geometry:
        id_mask.add(data[data.intersects(polygon)])

    return data.loc[list(id_mask)]


def filter_gdf_from_from_gdf_filter_own(
    data: gpd.GeoDataFrame, filter_data: gpd.GeoDataFrame, flag_only: bool = False
) -> gpd.GeoDataFrame:
    logger.info("Starting to filter data from polygons")
    id_mask = set()
    for i in range(len(filter_data)):
        # for i in range(2):
        if i % 100 == 0:
            logger.info(f"Processing polygons {((i / len(filter_data)) * 100):.2f}% complete")
        mask = data.within(filter_data.loc[i, "geometry"])
        id_mask.update(data[mask].index)

    indicis = list(id_mask)
    if flag_only:
        flagged_data = data.copy()
        flagged_data["affected"] = False
        flagged_data.loc[indicis, "flooded"] = True
        return flagged_data

    return data.loc[indicis]
